### ISSUE TITLE
WebSocket is closed before the connection is established.

### ISSUE THREAD

**Issue by jerearaujo03** [petronetto/laravel-realtime-chat#1]
I've installed the app but real-time isn't working. The JS console shows `WebSocket is closed before the connection is established.`

**Comment by petronetto** [comment]
Hey @jerearaujo03! I updated and now is working fine.
In `config/broadcasting.php` change the Pusher configs as bellow:

```php
        'pusher' => [
            'driver'  => 'pusher',
            'key'     => env('PUSHER_APP_KEY'),
            'secret'  => env('PUSHER_APP_SECRET'),
            'app_id'  => env('PUSHER_APP_ID'),
            'options' => [
                'cluster'   => env('PUSHER_CLUSTER'),
                'encrypted' => true,
            ],
        ],
```

You will need update the `resources/assets/js/bootstrap.js` to:

```js
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: 'YOUR_PUSHER_APP_KEY',
    cluster: 'YOUR_PUSHER_CLUSTER',
    encrypted: true
});
```
In  your `.env` add the you `PUSHER_CLUSTER`

Finally, run `composer update -o` to update the dependencies.
