### ISSUE TITLE
Real time

### ISSUE THREAD

**Issue by Legend23** [petronetto/laravel-realtime-chat#2]
Hello, 

I tried to install like in the description. 

ALL il fine, juste some troubles with the "real time". 
When i sent a message, I have to refresh the page to see it. 

I don't know where's the problem.

**Comment by petronetto** [comment]
@Legend23 I'm quite sure that is something about your Pusher account or your javascript code, please check the console logs in your browser, also, maybe you need to update the code, my last update was about 9 months ago.

When I have some time I'll check, but for now, you can follow the previous instructions and try Google the log errors.

**Comment by Legend23** [comment]
Thank you very much for all.
